audit_header: false
title: '-- MARKET -- Real Estate Video Blog with Jeff Wheatley'
description: >-
  Our mission at Keller Williams Capital Properties is to be your best resource
  for -- MARKET -- real estate advice. Whether you are a buyer, seller, or
  investor, our team of professionals can answer any questions you might have
  about real estate. If you are looking to buy or sell a home, you can get all
  the information and the latest updates, tips, and tricks from The Keller
  Williams Capital Properties, your professional -- MARKET -- Real Estate
  Agents.
show_custom_links: false
custom_links:
  - title:
    url:
client:
  name: Jeff Wheatley
  title: The Wheatley Group
  license_number:
  about_markdown: >-
    Jeff Wheatley is passionate about serving his clients transform their lives
    through real estate. His extensive background in real estate, finance, and
    life coaching enables him to draw from a deep well of life experience as he
    helps his clients make long term, intelligent decisions. In a shifting real
    estate market and changing landscape, his expertise and and focus on long
    terms goals provide a rare breed of service.


    Described by his peers and clients as smart, insightful and determined, Jeff
    goes beyond expectations in serving his clients. Jeff has has re-engineered
    the home seller process. He modeled his process after the best marketing
    practices in all industries. As a specific example, Jeff’s team launches a
    property through a carefully curated process with similarities to Apple’s
    launch process. His process builds anticipation and desire similar to the
    launch of iPhone 10XS. Contrast that to the last majority of his competition
    simple list a property by simply pray it sells.
  market: DC Metro
  brand: Jeff Wheatley Homes
  brokerage: Re/Max Realty Services
  address: '20 West Gude Drive #200 Rockville Md. 20850'
  phone: 240-731-7578
  phone_type: Direct
  phone2: 301-251-1221
  phone2_type: Office
  email: Jeff@JeffWheatleyHomes.com
  url: 'http://www.JeffWheatleyHomes.com'
CTAs:
  first_CTA_text: Sell For 18% More
  first_CTA_URL: 'https://www.jeffwheatleyhomes.com/sell-for-18-more/'
  second_CTA_text: Home Search
  second_CTA_URL: 'https://www.jeffwheatleyhomes.com/listings-search/#/2033763787'
sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: Sell For 18% More
    CTA_text: We sell for up to 18 Percent more than the average real estate agent.
    CTA_link_text: Contact us to ask how
    CTA_url: 'https://www.jeffwheatleyhomes.com/sell-for-18-more/'
second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: Looking for a -- MARKET -- Home?
    CTA_text2: Search the entire MLS for your -- MARKET -- home.
    CTA_link_text2: Search the MLS
    CTA_url2: 'https://www.jeffwheatleyhomes.com/listings-search/#/2033763787'
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: 'http://fillmurray.com/200/200'
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: 'http://eyegoop.com'
socials:
  review_sm_icons: true
  facebook_url: 'https://www.facebook.com/thewheatleygroup/'
  linkedin_url: 'https://www.linkedin.com/in/jeffreywheatley/'
  gplus_url:
  youtube_url: 'https://www.youtube.com/channel/UCYPybxxvq54sfNz83vntg7A'
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url: 'https://www.zillow.com/profile/Jeff-Wheatley/'
  trulia_url:
  yelp_url:
  podcast_url:
podcast:
  title: '-- MARKET -- Real Estate Podcast with Jeff Wheatley'
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the -- MARKET
    -- Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from Keller Williams Capital Properties -
    your professional -- MARKET -- Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in -- MARKET --,
    home selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: Jeff Wheatley
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 50
  hero_text: '-- MARKET -- Real Estate Video Blog'
  hero_background_hex: '#999999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#ed001a'
  theme_color: '#4c4d4f'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
navbar_colors:
  border_bottom:
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#ffffff'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: 'rgba(0, 0, 0, 0)'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'